### ISSUE TITLE
Download link for RDF/XML is broken (specification page)

### ISSUE THREAD

**Issue by k00ni** [oeg-upm/WoT-DT-ontology#18]
On https://oeg-upm.github.io/WoT-DT-ontology/OnToology/dt-ontology.ttl/documentation/index-en.html the link to the RDF/XML serialization is broken:

https://oeg-upm.github.io/WoT-DT-ontology/OnToology/dt-ontology.ttl/documentation/ontology.owl

![Bildschirmfoto vom 2024-04-03 08-34-43](https://github.com/oeg-upm/WoT-DT-ontology/assets/381727/dd9daddd-6538-4ebf-a1fc-d13561b5b07b)

**Comment by Salva5297** [comment]
Thanks for the info. 

We had some problems with the content negotiation. 

Now the redirection is correct. The file extension instead of being ".owl" is ".xml".

**Comment by k00ni** [comment]
Thank you for the quick fix.
